vich_uploader:
    db_driver: orm
    mappings:
        lesson_image:
            uri_prefix: /images/lessons
            upload_destination: '%kernel.project_dir%/public/images/lessons'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        course_image:
            uri_prefix: /images/courses
            upload_destination: '%kernel.project_dir%/public/images/courses'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        profile:
            uri_prefix: /images/profiles
            upload_destination: '%kernel.project_dir%/public/images/profiles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer